wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1659694217.007228
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.9.13
      5: 0.13.0
      8:
      - 3
      - 5
batch_size_linear:
  desc: null
  value: 128
batch_size_ssl:
  desc: null
  value: 512
common_space_dim:
  desc: null
  value: 1
device:
  desc: null
  value: cuda
dtype:
  desc: null
  value: torch.FloatTensor
emb_output_dim:
  desc: null
  value: 256
epoch_linear:
  desc: null
  value: 10
epoch_ssl:
  desc: null
  value: 20
from_strike_to_off:
  desc: null
  value: true
interpo_len:
  desc: null
  value: null
loss_fn:
  desc: null
  value: model.nx_xent_loss
lr_linear:
  desc: null
  value: 0.0001
lr_ssl:
  desc: null
  value: 0.0001
max_trial_num:
  desc: null
  value: 30
remove_trial_type:
  desc: null
  value: []
use_ratio:
  desc: null
  value: 100
